# Generated by Django 3.2.25 on 2025-06-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GatePass',
            fields=[
                ('GATEPASS_NO', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('GATEPASS_DATE', models.DateField()),
                ('PAYCODE', models.CharField(max_length=60)),
                ('NAME', models.CharField(blank=True, max_length=300, null=True)),
                ('DEPARTMENT', models.CharField(blank=True, max_length=300, null=True)),
                ('GATEPASS_TYPE', models.CharField(blank=True, max_length=150, null=True)),
                ('REMARKS', models.CharField(blank=True, max_length=765, null=True)),
                ('REQUEST_TIME', models.CharField(blank=True, max_length=60, null=True)),
                ('AUTH', models.CharField(blank=True, max_length=3, null=True)),
                ('AUTH1_BY', models.CharField(blank=True, max_length=24, null=True)),
                ('AUTH1_STATUS', models.CharField(blank=True, max_length=3, null=True)),
                ('AUTH1_DATE', models.DateField(blank=True, null=True)),
                ('AUTH1_REMARKS', models.CharField(blank=True, max_length=150, null=True)),
                ('FINAL_STATUS', models.CharField(blank=True, max_length=3, null=True)),
                ('OUT_TIME', models.DateTimeField(blank=True, null=True)),
                ('OUT_BY', models.CharField(blank=True, max_length=60, null=True)),
                ('IN_TIME', models.DateTimeField(blank=True, null=True)),
                ('IN_BY', models.CharField(blank=True, max_length=60, null=True)),
                ('INOUT_STATUS', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'GATEPASS',
                'managed': False,
            },
        ),
    ]
