# Generated by Django 5.2.3 on 2025-06-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepass_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='EMP_TYPE',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='LUNCH',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='UNIT_NAME',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
