# Generated by Django 3.2.25 on 2025-07-06 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatepass_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gatepass',
            table='GP_TEMP',
        ),
    ]
