# Generated by Django 3.2.25 on 2025-07-06 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatepass_app', '0002_alter_gatepass_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gatepass',
            table='GATEPASS',
        ),
    ]
