# Generated by Django 5.2.3 on 2025-07-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepass_app', '0002_gatepass_emp_type_gatepass_lunch_gatepass_unit_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='emp_details',
            fields=[
                ('paycode', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(blank=True, max_length=300, null=True)),
                ('department_name', models.CharField(blank=True, max_length=300, null=True)),
                ('unit_name', models.CharField(blank=True, max_length=300, null=True)),
                ('emp_type', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'EMP_DETAILS',
            },
        ),
        migrations.AddField(
            model_name='gatepass',
            name='duration',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
    ]
